from enum import Enum

class AuditAction(str,Enum):
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_ELIMINATED = "PRODUCT_ELIMINATED"
    CATEGORY_CREATED = "CATEGORY_CREATED"
    CATEGORY_ELIMINATED = "CATEGORY_ELIMINATED"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    USER_CREATED = "USER_CREATED"
    USER_ELIMINATED = "USER_ELIMINATED"
    ROLE_CHANGED = "ROLE_CHANGED"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED"
    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    ADMIN_PROMOTED = "ADMIN_PROMOTED"
    ADMIN_REMOVED = "ADMIN_REMOVED"
    
class AuditEntity(str,Enum):
    ADMIN = "ADMIN"
    USER = "USER"
    AUTH = "AUTH"
    ORDER = "ORDER"
    PAYMENT ="PAYMENT"
    INVENTORY = "INVENTORY"
    CATEGORY = "CATEGORY" 
    PRODUCT = "PRODUCT"   